name: Run Ardo for Linux

on:
  # https://github.community/t/reusable-workflows-secrets-and-environments/203695/18
  workflow_call:
    secrets:
      GH_PAT:
        required: true
  # workflow_dispatch and schedule are not working on non-default branch.
  workflow_dispatch:
  push:
    branches: 
      - dev
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: 
      - dev
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  repository_dispatch:
    types: ardo-build-linux
  schedule:
    # "At 14:00." 
    - cron: '0 6 * * *'

env:
  ARDOUR_VERSION: "latest"
  # available upload services: wetransfer.com, transfer.sh, file.io, 0x0.st
  UPLOAD_SERVICE: transfer.sh
  # ardour spurce code tar ball, need check its sha256sums.
  # https://community.ardour.org/srctar
  # https://fossies.org/linux/misc/Ardour-6.8.0.tar.bz2
  ARTIFACT_RETENTION_DAYS: 1

jobs:
  ardo-build:
    name: Ardo Build for Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              # Do not use Python 3.12 and above version.
              # 'distutils' and 'imp' packages are removed in python version 3.12, 
              # so some gtk build maybe fail.
              arch: x86_64,
              image_repo: debian,
              image_tag: bullseye
            }
          - {
              # gcc8
              arch: armhf,
              image_repo: debian,
              image_tag: buster
            }        
          - {
              # gcc8
              arch: arm64,
              image_repo: debian,
              image_tag: buster
            }
    container:
      image: ${{ matrix.config.image_repo }}:${{ matrix.config.image_tag }}
      options: -v ${{ github.workspace }}:/home/ardour:rw
    steps:
      - name: Install the Basic Dependencies
        if: matrix.config.arch == 'x86_64'
        shell: bash
        run: |
          apt-get -y -qq update && apt-get -y --no-install-recommends install \
            apt-transport-https \
            python3 \
            python3-pip \
            git \
            ca-certificates \
            rsync \
            unzip \
            itstool \
            build-essential \
            ccache \
            wget \
            python \
            python-dev \
            libxml-parser-perl \
            file \
            libx11-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxrender-dev \
            ocaml-nox \
            gperf \
            libxcb-render0-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libpulse-dev \
            libasound-dev \
            libjack-dev \
            ladspa-sdk \
            makeself \
            chrpath \
            mawk

      - name: Install the Basic Dependencies
        if: startsWith(matrix.config.arch, 'arm')
        shell: bash
        run: |
          apt-get -y -qq update && apt-get -y --no-install-recommends install \
            apt-transport-https \
            python3 \
            python3-pip \
            git \
            ca-certificates \
            rsync \
            unzip \
            itstool \
            build-essential \
            ccache \
            wget \
            python \
            python-dev \
            file \
            ocaml-nox \
            gperf \
            makeself \
            chrpath \
            mawk

      - name: Checkout Build Tools Source Code
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: magicalbox/ardo
          token: ${{ secrets.GH_PAT }} 
          fetch-depth: 0
          ref: dev
          path: '.'

      - name: Checkout Build Tools Source Code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: '.'

      # - name: Get Ardour Latest Release Source Code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'Ardour/ardour'
      #     fetch-depth: 1
      #     ref: ${{ env.ARDOUR_VERSION }}
      #     path: './src'
        
      - name: Get Ardour Latest Source Code
        uses: actions/checkout@v4
        with:
          repository: 'Ardour/ardour'
          fetch-depth: 0
          ref: 'master'
          path: './src'

      - name: Set ownership
        run: |
          chown -R $(id -u):$(id -g) /home/ardour    

      - name: Print GCC/G++ Version
        shell: bash
        run: |
          gcc --version
          g++ --version

      - name: Prepare
        shell: bash
        run: |
          chmod a+x /home/ardour/scripts/ardour-build-tools/waf
          chmod a+x /home/ardour/scripts/ardour-build-tools/rb-wscript
          chmod a+x /home/ardour/scripts/ardour-build-tools/vamp-wscript
          chmod a+x /home/ardour/src/waf

      - name: Set env
        if: matrix.config.arch == 'x86_64'
        shell: bash
        run: |
          echo "HOME=/home/ardour/linux-${{ matrix.config.arch }}" >> $GITHUB_ENV
          echo "PATH=/usr/lib/ccache:/home/ardour/linux-${{ matrix.config.arch }}/bin:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/bin/:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig/" >> $GITHUB_ENV
          echo "PYTHONPATH=./:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/python`python --version 2>&1 | cut -d ' ' -f 2 | cut -b 1-3`/site-packages/" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/" >> $GITHUB_ENV      

      - name: Set env
        if: matrix.config.arch == 'arm64'
        shell: bash
        run: |
          echo "XARCH=${{ matrix.config.arch }}" >> $GITHUB_ENV
          echo "SRCDIR=/home/ardour/tmp/winsrc"  >> $GITHUB_ENV
          echo "TMPDIR=/home/ardour/tmp" >> $GITHUB_ENV
          echo "ROOT=/home/ardour" >> $GITHUB_ENV
          echo "PATH=/usr/lib/ccache:/home/ardour/linux-${{ matrix.config.arch }}/bin:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/bin/:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/home/ardour/linux-${{ matrix.config.arch }}/stack/lib/pkgconfig/:/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig/" >> $GITHUB_ENV
          echo "PYTHONPATH=./:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/python`python --version 2>&1 | cut -d ' ' -f 2 | cut -b 1-3`/site-packages/" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/" >> $GITHUB_ENV

      - name: Set env
        if: matrix.config.arch == 'armhf'
        shell: bash
        run: |
          echo "XARCH=${{ matrix.config.arch }}" >> $GITHUB_ENV
          echo "SRCDIR=/home/ardour/tmp/winsrc"  >> $GITHUB_ENV
          echo "TMPDIR=/home/ardour/tmp" >> $GITHUB_ENV
          echo "ROOT=/home/ardour" >> $GITHUB_ENV
          echo "PATH=/usr/lib/ccache:/home/ardour/linux-${{ matrix.config.arch }}/bin:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/bin/:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/home/ardour/linux-${{ matrix.config.arch }}/stack/lib/pkgconfig/:/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig/" >> $GITHUB_ENV
          echo "PYTHONPATH=./:/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/python`python --version 2>&1 | cut -d ' ' -f 2 | cut -b 1-3`/site-packages/" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/ardour/linux-${{ matrix.config.arch }}/gtk/inst/lib/" >> $GITHUB_ENV   

      - name: Print env
        shell: bash
        run: |
          env

      - name: Install Build Stack
        if: matrix.config.arch == 'x86_64'
        shell: bash
        run: |
          bash /home/ardour/scripts/ardour-build-tools/build-stack

      - name: Install Build Stack & Compile & Package
        if: startsWith(matrix.config.arch, 'arm')
        shell: bash
        run: |
          bash /home/ardour/scripts/ardour-build-tools/x-armhf.sh

      - name: Compile
        if: matrix.config.arch == 'x86_64'
        # --depstack-root defaults to ~ 
        shell: bash
        run: |
          cd /home/ardour/src
          python3 ./waf configure --prefix=/usr --configdir=/etc --strict --ptformat --with-backends=jack,alsa,pulseaudio,dummy --libjack=weak --optimize --cxx11 --freedesktop
          python3 ./waf -j$(nproc)
          python3 ./waf i18n
          python3 ./waf install

      - name: Package
        if: matrix.config.arch == 'x86_64'
        shell: bash
        run: |
          cd /home/ardour/src/tools/linux_packaging
          bash ./build --public --harvid
          bash ./package --public --singlearch --makeself

      - name: Generate sha256sum & Upload Binary
        if: matrix.config.arch == 'x86_64'
        # Ardour-6.8.0-x86_64.run
        shell: bash
        run: |
          SHA256SUM=$(sha256sum /home/ardour/src/tools/linux_packaging/Ardour-*-${{ matrix.config.arch }}.run | cut -d ' ' -f 1)
          echo "${SHA256SUM}" > /home/ardour/src/tools/linux_packaging/Ardour-${{ env.ARDOUR_VERSION }}-${{ matrix.config.arch }}.run.sha256sum
          echo "sha256sum: ${SHA256SUM}"
          TEMP_DOWNLOAD_URL=$(sh /home/ardour/scripts/upload-services/${{ env.UPLOAD_SERVICE }}.sh /home/ardour/src/tools/linux_packaging/Ardour-*-${{ matrix.config.arch }}.run)
          echo Download URL is $TEMP_DOWNLOAD_URL      

      - name: Generate sha256sum & Upload Binary
        if: startsWith(matrix.config.arch, 'arm')
        # Ardour_arm64-6.8.0.run, Ardour_armhf-6.9.0.run, Ardour-7.0.rc2.20-armhf.run
        shell: bash
        run: |
          SHA256SUM=$(sha256sum /home/ardour/tmp/builds/A_Linux_${{ matrix.config.arch }}/Ardour-*-${{ matrix.config.arch }}.run | cut -d ' ' -f 1)
          echo "${SHA256SUM}" > /home/ardour/tmp/builds/A_Linux_${{ matrix.config.arch }}/Ardour-${{ env.ARDOUR_VERSION }}-${{ matrix.config.arch }}.run.sha256sum
          echo "sha256sum: ${SHA256SUM}"
          TEMP_DOWNLOAD_URL=$(sh /home/ardour/scripts/upload-services/${{ env.UPLOAD_SERVICE }}.sh /home/ardour/tmp/builds/A_Linux_${{ matrix.config.arch }}/Ardour-*-${{ matrix.config.arch }}.run)
          echo Download URL is $TEMP_DOWNLOAD_URL

      - name: Upload Artifact
        if: matrix.config.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: Ardour-Linux-${{ matrix.config.arch }}-Artifact
          path: |
            ${{ github.workspace }}/src/tools/linux_packaging/Ardour-*-${{ matrix.config.arch }}.run
            ${{ github.workspace }}/src/tools/linux_packaging/Ardour-*-${{ matrix.config.arch }}.run.sha256sum
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Upload Artifact
        if: startsWith(matrix.config.arch, 'arm')
        uses: actions/upload-artifact@v4
        with:
          name: Ardour-Linux-${{ matrix.config.arch }}-Artifact
          path: |
            ${{ github.workspace }}/tmp/builds/[CMA]_Linux_${{ matrix.config.arch }}/Ardour-*-${{ matrix.config.arch }}.run
            ${{ github.workspace }}/tmp/builds/[CMA]_Linux_${{ matrix.config.arch }}/Ardour-*-${{ matrix.config.arch }}.run.sha256sum
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
