name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

# https://github.community/t/reusable-workflows-secrets-and-environments/203695/18
jobs:
  reuseable1:
    uses:  magicalbox/run-ardo/.github/workflows/build-for-linux.yml@dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  reuseable2:
    uses:  magicalbox/run-ardo/.github/workflows/build-for-macos.yml@dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  reuseable3:
    uses:  magicalbox/run-ardo/.github/workflows/build-for-windows.yml@dev
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
